version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major"]